[package]
name = "file_browser"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = "0.18"
crossterm = "0.23"
walkdir = "2"
chrono = "0.4"
open = "3.0.1"

[lib]
name = "file_browser_lib"
path = "src/lib.rs"
